//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EJEMPLO_PRACTICAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class elliot__1
    {
        public long idPersona { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public System.DateTime FechaNac { get; set; }
        public string Rfc { get; set; }
        public bool Activo { get; set; }
    }
}
